<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251116143510 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE algae (id UUID NOT NULL, name VARCHAR NOT NULL, age INT NOT NULL, health_points INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE aquarium (id UUID NOT NULL, name VARCHAR NOT NULL, turn_number INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE fish (id UUID NOT NULL, name VARCHAR NOT NULL, species VARCHAR(50) NOT NULL, sex VARCHAR(10) NOT NULL, age INT NOT NULL, health_points INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE algae');
        $this->addSql('DROP TABLE aquarium');
        $this->addSql('DROP TABLE fish');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
