parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    Symfony\Component\ObjectMapper\ObjectMapperInterface:
        alias: object_mapper
        public: true

    App\Domain\Service\RandomGeneratorInterface:
        alias: App\Infrastructure\Service\SymfonyRandomGenerator
        public: true
